services:
  app:
    depends_on:
      - db
    image: openjdk:17-jdk-slim
    container_name: todo-app
    build:
      context: .
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "ToDo-App-1.0.0.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todo_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    ports:
      - "8081:8081"

  db:
    image: mysql:8.0
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: